title:            West Africa Cycle Challange
tagline:          Sierra Leone to Liberia, in aid of Street Child
description:      A cycleride through Seirra Leone and Liberia.
url: https://pmrourkie.github.io/wacc

# Owner/author information
owner:
  name:           Richard Allen
  avatar:         avatar.png
  bio:            "Aesthete & Athlete"
  email:          rourkie@gmail.com
  twitter:        pmrourkie
  github:         pmrourkie
  instagram:      pmrourkie
  disqus:         balzac
  location:       "Lonodn, UK"
  # Plug in your disqus shortname!



# Open Graph customization
opengraph:
  locale:           en_US

# Links to include in top navigation
# For external links add external: true
links:
  - title: The Journey
    url: /
  - title: About
    url: /about
    external: true
  - title: Pictures
    url: /pictures
  - title: Donate
    url: https://west-africa-cycle-challenge-jun18.everydayhero.com/uk/west-africa-cycle-ride
    external: true   
  - title: Route
    url: /route
  

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
highlighter: rouge
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
